name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2050-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "79dd16ed-fc51-4548-bc09-10f0a8989c23"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
